# Screen ASER sediment data
# AMC 2021-03
# Screened against 2019 data to compare output - output matches what was generated by P.Mark (no organic or rad exceedances, 12 Mn exc, 1 Fe)

# Load libraries
library(readr)
library(readxl)
library(writexl)
library(dplyr)
library(tidyr)
library(lubridate)
library(magrittr)
library(stringr)

# import sediment data
sed <- read_csv('Data/ASER_sediment_2020.csv',
                col_types = list('sample_date' = col_date("%m/%d/%Y"))) %>%
                filter(best_value_flag == 'Y', !str_detect(validation_qualifier, '%R%')) %>%
                select(3:36) 

# import screening standards
#SSLs are for inorganic and organic
ssl <- read_excel('Data/RS11941_NMED SSLs June 2019_for_analysis.xlsx') %>%
          select(1:8) 

names(ssl) %<>%
  str_replace_all("\\s", "_") %>% tolower()

# Some SSLs need to be renamed to match sed data - confirmed with chemists that these matches are correct
ssl <- ssl %>%
  mutate(chemical = case_when(
    chemical == 'Mercury (elemental)' ~ 'Mercury',
    chemical == 'Chromium (Total)' ~ 'Chromium',
    chemical == 'Uranium (soluable salts)' ~ 'Uranium',
    TRUE ~ as.character(chemical)
  ))

ssl_tall <- ssl %>%
  pivot_longer(cols = c(3:8), names_to = 'SSL_cat', values_to = 'SSL_value')

# SALs are for rads
sal <- read_excel('Data/screening_action_limits.xlsx') %>%
  select(-6)

sal_tall <- sal %>%
  pivot_longer(cols = c(2:5), names_to = "SAL_cat", values_to = 'SAL_value')

# start with the SSLs and SALs, then deal with the BCGs and figure out if we want to use the recreational SSLs too 
# we will NOT be using recreational SSLs

# Rads - here do an inner join with SALs
rad_screen <- function(sediment_data){
  init_screen <- sediment_data %>%
    inner_join(sal_tall, by = c('parameter_name' = 'radionuclide')) %>%
    mutate(exceedance = ifelse((!is.na(SAL_value) & report_result > SAL_value & detect_flag == 'Y'), 1, 0)) 
  if (sum(init_screen$exceedance) == 0) {
    print('No radionuclide exceedances!')
  } else {
    init_screen_wide <- init_screen %>%
      select(-SAL_value) %>%
      pivot_wider(names_from = 'SAL_cat', values_from = 'exceedance') %>%
      mutate(exceed = ifelse(rowSums(across(35:38), na.rm = TRUE) >= 1, 1, 0))%>%
      group_by(location_id, parameter_code, parameter_name, sample_purpose) %>%
      summarize(analyses_n = n(), detect_n = sum(detect_flag == 'Y'), exceed_n = sum(exceed == 1))
    return(list(init_screen, init_screen_wide))
  }
}

rad_screen_results <- rad_screen(sed)

#########################################
# Inorganics and organics screened to SSLs - ASER text says that anything without an SSL gets screened to EPA standards 
# Need to look in to what those would be - for now, do an inner join, and figure that out later

# Might be easiest to do inorganic and organic separately 
# Inorgs can be joined by parameter_name, orgs need to be joined by parameter_code
ssl_inorg_screen <- function(sediment_data) {
  init_screen <- sediment_data %>% 
    filter(parameter_category == 'INORGANIC') %>%
    inner_join(ssl_tall, by = c('parameter_name' = 'chemical')) %>%
    mutate(exceedance = ifelse((!is.na(SSL_value) & report_result > SSL_value & detect_flag == 'Y'), 1, 0)) 
  if (sum(init_screen$exceedance) == 0) {
    print('No inorganic exceedances!')
  } else {
    init_screen_wide <- init_screen %>%
      select(-SSL_value) %>%
      pivot_wider(names_from = 'SSL_cat', values_from = 'exceedance') %>%
      mutate(exceed = ifelse(rowSums(across(36:41), na.rm = TRUE) >= 1, 1, 0))%>%
      group_by(location_id, parameter_code, parameter_name, sample_purpose) %>%
      summarize(analyses_n = n(), detect_n = sum(detect_flag == 'Y'), exceed_n = sum(exceed == 1))
    return(list(init_screen, init_screen_wide))
  }
}

inorg_screen_results <- ssl_inorg_screen(sed)

inorg_all_screen <- inorg_screen_results[[1]]
inorg_screen_counts <- inorg_screen_results[[2]]

# Save output
write_xlsx(inorg_all_screen, 'Output/sediment_inorganic_screening.xlsx')
write_xlsx(inorg_screen_counts, 'Output/sediment_inorganic_exc_counts.xlsx')

# Are there inorganics without an SSL?
test_inorg <- sed %>% 
  filter(parameter_category == 'INORGANIC') %>%
  left_join(ssl_tall, by = c('parameter_name' = 'chemical')) %>%
  filter(is.na(SSL_cat) & report_units == 'mg/kg')
# All inorganics have an SSL

###########
ssl_org_screen <- function(sediment_data) {
  init_screen <- sediment_data %>% 
    filter(parameter_category == 'ORGANIC') %>%
    inner_join(ssl_tall, by = c('parameter_code' = 'cas')) %>%
    mutate(exceedance = ifelse((!is.na(SSL_value) & report_result > SSL_value & detect_flag == 'Y'), 1, 0)) 
  if (sum(init_screen$exceedance) == 0) {
    print('No organic exceedances!')
  } else {
    init_screen_wide <- init_screen %>%
      select(-SSL_value) %>%
      pivot_wider(names_from = 'SSL_cat', values_from = 'exceedance') %>%
      mutate(exceed = ifelse(rowSums(across(36:41), na.rm = TRUE) >= 1, 1, 0))%>%
      group_by(location_id, parameter_code, parameter_name, sample_purpose) %>%
      summarize(analyses_n = n(), detect_n = sum(detect_flag == 'Y'), exceed_n = sum(exceed == 1))
    return(list(init_screen, init_screen_wide))
  }
}

org_screen_results <- ssl_org_screen(sed)

org_all_screen <- org_screen_results[[1]]
org_screen_counts <- org_screen_results[[2]]
# Note: looks like the PAHs have 2 analyses each instead of 1 - seems to be because 2 different analysis methods are used.
# Should be fine to keep everything as is.

# Save output
write_xlsx(org_all_screen, 'Output/sediment_organic_screening.xlsx')
write_xlsx(org_screen_counts, 'Output/sediment_organic_exc_counts.xlsx')

# Are there organics without an SSL?
test_org <- sed %>% 
  filter(parameter_category == 'ORGANIC') %>%
  left_join(ssl_tall, by = c('parameter_code' = 'cas')) %>%
  filter(is.na(SSL_cat) & report_units == 'mg/kg') %>%
  select(parameter_code, parameter_name) %>%
  distinct()

# write_excel_csv(test_org, "Output/sed_org_no_SSL.csv")

# There are 225 organics without an SSL - lots of PCBs

#########################################
# For any chemical that didn't have an SSL/SAL, screen against EPA RSL (THQ=0.1)
rsl <- read_excel('Data/EPA_RSL_THQ0.1_for_analysis.xlsx') %>%
  select(1:6) %>%
  rename(residential_key = key...4, industrial_key = key...6) 

rsl_tall <- rsl %>%
  select(1:3,5) %>%
  pivot_longer(cols = c(3,4), names_to = 'RSL_cat', values_to = 'RSL_value')

rsl_key <- rsl %>%
  select(1:2, 4,6) %>%
  pivot_longer(cols = c(3,4), names_to = 'key_name', values_to = 'key_val') %>%
  select(3,4)

rsl_tall <- bind_cols(rsl_tall, rsl_key) 
rm(rsl_key)

# All the inorganics have an SSL, but quite a few organics don't
# org_no_ssl <- sed %>% 
#   filter(parameter_category == 'ORGANIC') %>%
#   left_join(ssl_tall, by = c('parameter_code' = 'cas')) %>%
#   filter(is.na(SSL_cat) & report_units == 'mg/kg') %>%
#   select(1:34) %>%
#   inner_join(rsl_tall, by = c('parameter_code' = 'CAS No.')) %>%
#   filter(parameter_name != 'Total PCB') %>%
#   mutate(exceedance = ifelse((!is.na(RSL_value) & report_result > RSL_value & detect_flag == 'Y'), 1, 0)) 
# 
# org_no_ssl_wide <- org_no_ssl %>%
#   select(-RSL_value, -key_name, -key_val) %>%
#   pivot_wider(names_from = 'RSL_cat', values_from = 'exceedance') %>%
#   mutate(exceed = ifelse(rowSums(across(36:37), na.rm = TRUE) >= 1, 1, 0))%>%
#   group_by(location_id, parameter_code, parameter_name, sample_purpose) %>%
#   summarize(analyses_n = n(), detect_n = sum(detect_flag == 'Y'), exceed_n = sum(exceed == 1))

rsl_org_screen <- function(sediment_data) {
  init_screen <- sediment_data %>% 
    filter(parameter_category == 'ORGANIC') %>%
    left_join(ssl_tall, by = c('parameter_code' = 'cas')) %>%
    filter(is.na(SSL_cat) & report_units == 'mg/kg') %>%
    select(1:34) %>%
    inner_join(rsl_tall, by = c('parameter_code' = 'CAS No.')) %>%
    filter(parameter_name != 'Total PCB') %>%
    mutate(exceedance = ifelse((!is.na(RSL_value) & report_result > RSL_value & detect_flag == 'Y'), 1, 0)) 
  if (sum(init_screen$exceedance) == 0) {
    print('No RSL organic exceedances!')
  } else {
    init_screen_wide <- init_screen %>%
      select(-RSL_value, -key_name, -key_val) %>%
      pivot_wider(names_from = 'RSL_cat', values_from = 'exceedance') %>%
      mutate(exceed = ifelse(rowSums(across(36:37), na.rm = TRUE) >= 1, 1, 0))%>%
      group_by(location_id, parameter_code, parameter_name, sample_purpose) %>%
      summarize(analyses_n = n(), detect_n = sum(detect_flag == 'Y'), exceed_n = sum(exceed == 1))
    return(list(init_screen, init_screen_wide))
  }
}

rsl_results <- rsl_org_screen(sed)


# A lot of the parameters remaining are Total PCBs, but I think the ASER says we don't screen Total PCBs in sed, only congeners... 
# For now, have filtered out Total PCBs

######################################
# Screen against BCGs with McNaughton site-specific values
# Sediment are screened against terrestrial and riparian values

bcg <- read_excel('Data/DOE_BCGs_for_sediment_analysis.xlsx')
names(bcg) %<>%
  str_replace_all("\\s", "_") %>% tolower()

bcg_screen <- function(sediment_data){
  init_screen <- sediment_data %>%
    inner_join(bcg, by = c('parameter_name' = 'radionuclide')) %>%
    mutate(exceedance = ifelse((!is.na(bcg_pci_g) & report_result > bcg_pci_g & detect_flag == 'Y'), 1, 0)) 
  if (sum(init_screen$exceedance) == 0) {
    print('No BCG exceedances!')
  } else {
    init_screen_wide <- init_screen %>%
      select(-bcg_pci_g) %>%
      pivot_wider(names_from = 'organism_responsible_for_limiting_dose_in_soil', values_from = 'exceedance') %>%
      mutate(exceed = ifelse(rowSums(across(35:38), na.rm = TRUE) >= 1, 1, 0))%>%
      group_by(location_id, parameter_code, parameter_name, sample_purpose) %>%
      summarize(analyses_n = n(), detect_n = sum(detect_flag == 'Y'), exceed_n = sum(exceed == 1))
    return(list(init_screen, init_screen_wide))
  }
}

bcg_results <- bcg_screen(sed)

#########################################
# Screen against Ryti Backgrounds
ryti <- read_excel('Data/Ryti Soil Backgrounds.xlsx') %>%
  select(1:4) %>%
  rename(parameter_name = `mg/kg units`)

ryti_screen <- function(sediment_data) {
  init_screen <- sediment_data %>%
    inner_join(ryti, by = c('parameter_name', 'report_units')) %>%
    mutate(exceedance = ifelse((!is.na(SED) & report_result > SED & detect_flag == 'Y'), 1, 0))
  if (sum(init_screen$exceedance) == 0) {
    print('No Ryti background exceedances!')
  } else {
    return(init_screen)
  }
}

ryti_results <- ryti_screen(sed)

# Save output
write_xlsx(ryti_results, 'Output/ryti_sed_screening.xlsx')


# Summary - sediment data are screened against NMED SSLs for organics and inorganics
# There are both organic and inorganic exceedances
# Rads are screened against LANL SALs and DOE BCGs with McNaughton corrections
# No rads exceeded SALs or BCGs
# Anything that didn't have an SSL was screened against EPA RSLs 
# No RSL exceedances
# Inorganics were also screened against Ryti backgrounds for reference 
# Not surprisingly, quite a few background exceedances
