# Screen ASER sediment data
# AMC 2021-03
# Screened against 2019 data to compare output - output matches what was generated by P.Mark (no organic or rad exceedances, 12 Mn exc, 1 Fe)

# Load libraries
library(readr)
library(readxl)
library(dplyr)
library(tidyr)
library(lubridate)
library(magrittr)
library(stringr)

# import sediment data
sed <- read_csv('Data/ASER_sediment_2020.csv',
                col_types = list('sample_date' = col_date("%m/%d/%Y"))) %>%
                select(3:36) %>%
                filter(validation_qualifier != 'R')

# import screening standards
#SSLs are for inorganic and organic
ssl <- read_excel('Data/RS11941_NMED SSLs June 2019_for_analysis.xlsx') %>%
          select(1:8) 

names(ssl) %<>%
  str_replace_all("\\s", "_") %>% tolower()

ssl_tall <- ssl %>%
  pivot_longer(cols = c(3:8), names_to = 'SSL_cat', values_to = 'SSL_value')

# SALs are for rads
sal <- read_excel('Data/screening_action_limits.xlsx') %>%
  select(-6)

sal_tall <- sal %>%
  pivot_longer(cols = c(2:5), names_to = "SAL_cat", values_to = 'SAL_value')

# start with the SSLs and SALs, then deal with the BCGs and figure out if we want to use the recreational SSLs too

# Rads - here do an inner join with SALs
rad_screen <- function(sediment_data){
  init_screen <- sediment_data %>%
    inner_join(sal_tall, by = c('parameter_name' = 'radionuclide')) %>%
    mutate(exceedance = ifelse((!is.na(SAL_value) & report_result > SAL_value & detect_flag == 'Y'), 1, 0)) 
  if (sum(init_screen$exceedance) == 0) {
    print('No radionuclide exceedances!')
  } else {
    init_screen_wide <- init_screen %>%
      select(-SAL_value) %>%
      pivot_wider(names_from = 'SAL_cat', values_from = 'exceedance') %>%
      mutate(exceed = ifelse(rowSums(across(35:38), na.rm = TRUE) >= 1, 1, 0))%>%
      group_by(location_id, parameter_code, parameter_name, sample_purpose) %>%
      summarize(analyses_n = n(), detect_n = sum(detect_flag == 'Y'), exceed_n = sum(exceed == 1))
    return(init_screen_wide)
  }
}

rad_screen_results <- rad_screen(sed)

#########################################
# Inorganics and organics screened to SSLs - ASER text says that anything without an SSL gets screened to EPA standards 
# Need to look in to what those would be - for now, do an inner join, and figure that out later

# Might be easiest to do inorganic and organic separately 
# Inorgs can be joined by parameter_name, orgs need to be joined by parameter_code
ssl_inorg_screen <- function(sediment_data) {
  init_screen <- sediment_data %>% 
    filter(parameter_category == 'INORGANIC') %>%
    inner_join(ssl_tall, by = c('parameter_name' = 'chemical')) %>%
    mutate(exceedance = ifelse((!is.na(SSL_value) & report_result > SSL_value & detect_flag == 'Y'), 1, 0)) 
  if (sum(init_screen$exceedance) == 0) {
    print('No inorganic exceedances!')
  } else {
    init_screen_wide <- init_screen %>%
      select(-SSL_value) %>%
      pivot_wider(names_from = 'SSL_cat', values_from = 'exceedance') %>%
      mutate(exceed = ifelse(rowSums(across(36:41), na.rm = TRUE) >= 1, 1, 0))%>%
      group_by(location_id, parameter_code, parameter_name, sample_purpose) %>%
      summarize(analyses_n = n(), detect_n = sum(detect_flag == 'Y'), exceed_n = sum(exceed == 1))
    return(init_screen_wide)
  }
}

inorg_screen_results <- ssl_inorg_screen(sed)

# Are there inorganics without an SSL?
test_inorg <- sed %>% 
  filter(parameter_category == 'INORGANIC') %>%
  left_join(ssl_tall, by = c('parameter_name' = 'chemical')) %>%
  filter(is.na(SSL_cat) & report_units == 'mg/kg')

# Mercury, Chromium, Uranium --> naming issue I need to check on

###########
ssl_org_screen <- function(sediment_data) {
  init_screen <- sediment_data %>% 
    filter(parameter_category == 'ORGANIC') %>%
    inner_join(ssl_tall, by = c('parameter_code' = 'cas')) %>%
    mutate(exceedance = ifelse((!is.na(SSL_value) & report_result > SSL_value & detect_flag == 'Y'), 1, 0)) 
  if (sum(init_screen$exceedance) == 0) {
    print('No organic exceedances!')
  } else {
    init_screen_wide <- init_screen %>%
      select(-SSL_value) %>%
      pivot_wider(names_from = 'SSL_cat', values_from = 'exceedance') %>%
      mutate(exceed = ifelse(rowSums(across(36:41), na.rm = TRUE) >= 1, 1, 0))%>%
      group_by(location_id, parameter_code, parameter_name, sample_purpose) %>%
      summarize(analyses_n = n(), detect_n = sum(detect_flag == 'Y'), exceed_n = sum(exceed == 1))
    return(init_screen_wide)
  }
}

org_screen_results <- ssl_org_screen(sed)

# Are there organics without an SSL?
test_org <- sed %>% 
  filter(parameter_category == 'ORGANIC') %>%
  left_join(ssl_tall, by = c('parameter_code' = 'cas')) %>%
  filter(is.na(SSL_cat) & report_units == 'mg/kg') %>%
  select(parameter_code, parameter_name) %>%
  distinct()

# write_excel_csv(test_org, "Output/sed_org_no_SSL.csv")

# There are 225 organics without an SSL - lots of PCBs

######################################
# Screen against BCGs with McNaughton site-specific values
# Sediment are screened against terrestrial and riparian values

bcg <- read_excel('Data/DOE_BCGs_for_sediment_analysis.xlsx')
names(bcg) %<>%
  str_replace_all("\\s", "_") %>% tolower()

bcg_screen <- function(sediment_data){
  init_screen <- sediment_data %>%
    inner_join(bcg, by = c('parameter_name' = 'radionuclide')) %>%
    mutate(exceedance = ifelse((!is.na(bcg_pci_g) & report_result > bcg_pci_g & detect_flag == 'Y'), 1, 0)) 
  if (sum(init_screen$exceedance) == 0) {
    print('No BCG exceedances!')
  } else {
    init_screen_wide <- init_screen %>%
      select(-bcg_pci_g) %>%
      pivot_wider(names_from = 'organism_responsible_for_limiting_dose_in_soil', values_from = 'exceedance') %>%
      mutate(exceed = ifelse(rowSums(across(35:38), na.rm = TRUE) >= 1, 1, 0))%>%
      group_by(location_id, parameter_code, parameter_name, sample_purpose) %>%
      summarize(analyses_n = n(), detect_n = sum(detect_flag == 'Y'), exceed_n = sum(exceed == 1))
    return(init_screen_wide)
  }
}

bcg_results <- bcg_screen(sed)

